apiVersion: v1
entries:
  evc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-03T12:11:15.4427283Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 3baf730c5498321c7bf12507e3fd46656bd8cc2a11e195605efd6526dc157958
    home: evc.zaakonline.nl
    icon: evc.zaakonline.nl
    name: evc
    urls:
    - evc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-03T12:11:15.4345983Z"
